---
title: "Project proposal"
format: 
  html:
    toc: true
    toc-title: Contents
    code-fold: show
    self-contained: true
jupyter: python3
---

## Instructions {-}

1. Please answer the following questions as part of your project proposal.

2. Write your answers in the *Markdown* cells of the Jupyter notebook. You don't need to write any code, but if you want to, you may use the *Code* cells.

3. Use [Quarto](https://quarto.org/docs/output-formats/html-basics.html) to print the *.ipynb* file as HTML. You will need to open the command prompt, navigate to the directory containing the file, and use the command: `quarto render filename.ipynb --to html`. Submit the HTML file.

4. The project proposal is worth 8 points, and is due on **18th April 2023 at 11:59 pm**. 

5. You must make one submission as a group, and not individually.

6. Maintaining a GitHub repository is optional, though encouraged for the project.

7. Share the link of your project's GitHub repository [here](https://docs.google.com/spreadsheets/d/1khao3unpj_vsx4kOSg_Zzo77YK1UWL2w73Oa0aAirOo/edit#gid=0) (optional).

# 1) Team name
Mention your team name.

*(0 points)*

Geriatrics

# 2) Member names
Mention the names of your team members.

*(0 points)*

Albert Wang, Nate Kim, Grant Li

# 3) Link to the GitHub repository (optional)
Share the link of the team's project repository on GitHub.

Also, put the link of your project's GitHub repository [here](https://docs.google.com/spreadsheets/d/1khao3unpj_vsx4kOSg_Zzo77YK1UWL2w73Oa0aAirOo/edit#gid=0).

We believe there is no harm in having other teams view your GitHub repository. However, if you don't want anyone to see your team's work, you may make the repository *Private* and add your instructor and graduate TA as *Colloborators* in it.

*(0 points)*

# 4) Topic
Mention the topic of your course project.

*(0 points)*

The topic of our course project is airline delays.

# 5) Problem statement

*(4 points)*

Explain the problem statement. The problem statement must include:

## 5a) The problem

In 2021, airline delays in the USA cost the economy [$80.52 per minute](https://www.airlines.org/dataset/u-s-passenger-carrier-delay-costs/#:~:text=In%202021%2C%20the%20average%20cost,levels%20to%20%2428.14%20per%20minute.). Flight delays are a burden to both the airlines and passengers, as they have the potential to cause a multitude of problems, including disrupted travel plans, lost revenue from travel-related industries, and safety concerns such as passengers being stranded in airports. Being able to predict whether a flight will be delayed can help everyone involved make contingency plans for the event of a delay.

## 5b) Type of response
Is it about predicting a continuous response or a binary response or a combination of both?

We will be predicting a binary response, 1 for delayed flights and 0 for punctual flights. The original variable in the dataset is the number of minutes a flight is delayed. The US FAA considers a flight delayed if its delay is 15 or more minutes, so we will transform the delay variable accordingly.

## 5c) Performance metric
How will you assess model accuracy?

  - If it is a classification problem, then which measure(s) will you optimize for your model – precision, recall, false negative rate (FNR), accuracy, ROC-AUC etc., and why?
  - If it is a regression problem, then which measure(s) will you optimize for your model – RMSE (Root mean squared error), MAE (mean absolute error), maximum absolute error etc., and why?

We seek to optimize the false negative rate because it is problematic if a flight is predicted to arrive on time but ends up delayed. However, we will still consider other performance metrics like precision and recall since the overall model performance matters.

## 5d) Naive model accuracy
What is the accuracy of the naive model (Standard deviation of response in case of continuous response / proportion of the majority class in case of classification model)

In [3]:
import pandas as pd
data = pd.DataFrame()
years = range(2002, 2009)
for year in years:
    data = pd.concat([data, pd.read_csv(f'archive/{year}.csv', encoding='latin-1')])
data.head()

/var/folders/78/287t_xwn4jj_fts7vlrhv3z80000gq/T/ipykernel_27967/1990285795.py:5: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.concat([data, pd.read_csv(f'archive/{year}.csv', encoding='latin-1')])

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2002,1,13,7,2231.0,2235,2342.0,2353,US,723,...,3.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2002,1,14,1,2230.0,2235,2347.0,2353,US,723,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2002,1,15,2,2230.0,2235,2342.0,2353,US,723,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2002,1,16,3,2230.0,2235,2340.0,2353,US,723,...,3.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2002,1,17,4,2227.0,2235,2345.0,2353,US,723,...,5.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [5]:
data.shape

(43014119, 29)

In [6]:
sample = data.sample(10000)
sample.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,10000.00000,10000.000000,10000.000000,10000.000000,9813.000000,10000.000000,9802.000000,10000.000000,10000.000000,9802.000000,...,10000.000000,9981.000000,9982.000000,10000.00000,10000.00000,7742.000000,7742.000000,7742.000000,7742.000000,7742.000000
mean,2004.84830,6.311100,15.688700,3.932800,1342.336391,1336.047000,1492.279433,1501.733000,2011.720900,125.723016,...,727.809800,6.834686,15.747946,0.01870,0.00110,3.645957,0.603074,3.768923,0.051020,4.241798
std,1.78701,3.442862,8.719851,1.970196,476.563231,465.255825,498.448421,479.334662,1871.348092,71.824062,...,576.769678,25.476413,11.097819,0.13547,0.03315,21.138138,7.638243,16.266637,1.598461,19.279562
min,2002.00000,1.000000,1.000000,1.000000,1.000000,10.000000,1.000000,1.000000,1.000000,21.000000,...,28.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2003.00000,3.000000,8.000000,2.000000,930.000000,925.000000,1112.250000,1118.000000,573.000000,74.000000,...,318.000000,4.000000,10.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2005.00000,6.000000,16.000000,4.000000,1329.000000,1325.000000,1516.000000,1520.000000,1399.000000,107.000000,...,569.000000,5.000000,13.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2006.00000,9.000000,23.000000,6.000000,1734.000000,1725.000000,1915.000000,1913.000000,2906.000000,156.000000,...,956.000000,8.000000,19.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2008.00000,12.000000,31.000000,7.000000,2400.000000,2359.000000,2437.000000,2359.000000,9573.000000,673.000000,...,4962.000000,1450.000000,192.000000,1.00000,1.00000,711.000000,364.000000,387.000000,82.000000,409.000000

In [7]:
sample['Delay'] = sample['ArrDelay'] > 15
sample['Delay'].value_counts()

False    8066
True     1934
Name: Delay, dtype: int64

The data is unbalanced with more flights being on-time than delayed, so we will need to stratify the data.

# 6) Data

## 6a) Source
What data sources will you use, and how will the data help solve the problem? Explain.
If the data is open source, share the link of the data.

*(0.5 point)*

We are using an open-source dataset of airlines from the [2009 ASA Statistical Computing and Graphics Data Expo](https://community.amstat.org/jointscsg-section/dataexpo/dataexpo2009). It is also [available on Kaggle](https://www.kaggle.com/datasets/wenxingdi/data-expo-2009-airline-on-time-data). The data consists of commercial flights within the US from 1987 to 2008. We will be using data from 2002 to 2008, given that the sample size is more than sufficient.

## 6b) Response & predictors
What is the response, and mention some of the predictors.

*(0.5 point)*

Response: ArrDelay arrival delay, in minutes
- Response will be transformed to Delay: yes/no (1/0), yes being if ArrDelay is greater than 15 min.

Predictors: 
- Years 2002-2008
- Month, 
- Day of month 
- Day of week 
- CRSDepTime scheduled departure time 
- UniqueCarrier unique carrier code 
- FlightNum flight number 
- TailNum plane tail number 
- CRS elapsed time
- AirTime in minutes 
- Airport origin
- Airport destination
- Distance in miles 
- Taxi in time
- Taxi out time
- Type of delay (potentially using)
- Carrier delay 
- Weather delay 
- NAS delay
- Security delay
- Late aircraft delay

## 6c) Size
What is the number of continuous predictors, categorical predictors, and observations in your dataset(s). If you are using multiple datasets, please provide the information for each dataset. When counting predictors, count only those that have sufficient non-missing values, and will be useful.

*(1 point)*

The original dataset has 120 million observations, with 29 variables, of which we will use around 15 as predictors. Six are discrete or categorical, and 7 are continuous. It is possible that we will append a weather dataset to see how weather affects flight delays since this is likely a prominent factor. However, this would be a nuanced task since we would need to account for weather at the origin, destination, and flight path.

# 7) Existing solutions
Are there existing solutions of your problem? Almost all Kaggle datasets have exisiting solutions. If yes, then how do you plan to build up on those solutions? **What is the highest model accuracy / performance achieved in the existing solutions?**

*(1 point)*

There were no existing and publicly available solutions to be found for this dataset. All previous work on the dataset that we found were simply data visualizations, exploratory data analysis, and also some SQL exercises on data retrieval.

# 8) Stakeholders

Who are the stakeholders, and how will your project benefit them? Explain.

*(1 point)*

The stakeholders of this project are airline passengers, commercial airlines, pilots, and flight attendants. Delayed flights affect the schedules of millions, if not billions of people in the world in a year. Not only are delayed flights problematic for scheduling purposes, they could also accrue more costs in the form of missed connecting flights, wasted time, and disrupted schedules for passengers and airline personnel alike. Delayed flights waste people’s time and money, who are sometimes on tight schedules or have important business. Therefore, it is important to be able to predict when a delayed flight will happen, so less people will experience flight delays.

# 9) Work-split
*(This question is answered for you)*

How do you plan to split the project work amongst individual team members?

We will learn to develop and tune the following models in the STAT303 sequence:

1. MARS - n/a

2. Decision trees with cost-complexity pruning - Albert

3. Bagging (Bagging MARS / decision trees) - Nate

4. Random Forests - Albert

5. AdaBoost - Grant

6. Gradient boosting - Grant

7. XGBoost - Nate

8. Lasso / Ridge / Stepwise selection - Nate

Each team member is required to develop and tune at least one of the above models. In the end, the team will combine all the developed models to create a model more accurate than each of the individual models.

*(0 points)*